# Generated by Django 5.0.2 on 2024-02-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plandetail_choice_text'),
        ('post', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='plan.plandetail'),
            preserve_default=False,
        ),
    ]
