# Generated by Django 5.0.2 on 2024-02-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_district_region_alter_post_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
