# Generated by Django 5.0.2 on 2024-02-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='json',
        ),
    ]
