# Generated by Django 5.0.2 on 2024-02-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='place_holder',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
