# Generated by Django 5.0.2 on 2024-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_alter_option_place_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
