# Generated by Django 5.0.2 on 2024-02-18 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0003_alter_option_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postoptionvalue',
            old_name='value',
            new_name='option_value',
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='option.option'),
        ),
        migrations.AlterUniqueTogether(
            name='postoptionvalue',
            unique_together={('post_option', 'option_value')},
        ),
    ]
